accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

send/urls.py
from django.urls import path

from . import views

app_name = 'send'

urlpatterns = [
    path('', views.index),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('send/', include('send.urls', namespace='send')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'Профиль пользователя {self.user.username}'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повтор пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birthdate',)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.decorators import login_required
from accounts.forms import LoginForm, RegistrationForm, UserEditForm, ProfileEditForm
from accounts.models import Profile
from django.conf import settings
from django.core.mail import send_mail
"""Вход в профиль пользователя"""


class LoginView(View):

    def my_render(self, request, form):
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'],
            )
            if user is None:
                return HttpResponse('Неправильный логин и/или пароль')

            if not user.is_active:
                return HttpResponse('Ваш аккаунт заблокирован')

            login(request, user)
            return HttpResponse('Добро пожаловать! Успешный вход')

        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return self.my_render(request, form)


"""Регистрация пользователя"""


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)

            return render(request, 'accounts/registration_complete.html', {'new_user': new_user})
    else:
        form = RegistrationForm()

    return render(request, 'accounts/register.html', {'user_form': form})


"""Изменение параметров пользоваетля"""
"""Фото можно вставить только через админку"""


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'accounts/edit.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменить профиль{% endblock %}

{% block main_content %}
    <h1>Изменить профиль</h1>
    <p>Используйте форму ниже, чтобы что-то поменять в профиле:</p>
    <form action="." method="POST" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Войдите{% endblock %}

{% block main_content %}
    <h1>Вход</h1>
    <p>Введите логин/пароль:</p>
    <form action="." method="POST" class="login">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Зарегистрироваться{% endblock %}

{% block main_content %}
    <h1>Создать аккаунт</h1>
    <p>Воспользуйтесь следующей формой:</p>
    <form action="." method="POST">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Создать"></p>
    </form>
{% endblock %}

accounts/templates/accounts/registration_complete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ура! Успех{% endblock %}

{% block main_content %}
    <h1>Всё готово, {{ new_user.first_name }}!</h1>
    <p>Ваш аккаунт был создал, теперь можно
        <a href="{% url 'accounts:login' %}">
            залогиниться
        </a>
        .
    </p>
{% endblock %}