send/urls.py
from django.urls import path

from . import views

app_name = 'send'

urlpatterns = [
    path('', views.index),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailView.as_view(), name='details'),
    path('edit/<int:pk>', views.TaskEditView.as_view(), name='edit'),
    path('export/', views.ExportTaskView.as_view(), name='export'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('send/', include('send.urls', namespace='send')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, 'Выспокий приоритет'),
        (PRIORITY_MEDIUM, 'Средний приоритет'),
        (PRIORITY_LOW, 'Низский приоритет'),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField('Выполнено', default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks')
    priority = models.IntegerField('Приоритет', choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('tasks:details', args=[self.pk])

    class Meta:
        ordering = ('-created',)

tasks/forms.py
from django import forms

from tasks.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label='')


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description', 'priority')
        labels = {'description': 'Описание', 'priority': ''}


class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label='Высокая важность', initial=True, required=False,
    )
    prio_medium = forms.BooleanField(
        label='Средняя важность', initial=True, required=False,
    )
    prio_low = forms.BooleanField(
        label='Низкая важность', initial=True, required=False,
    )

tasks/views.py
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from tasks.models import TodoItem
from tasks.forms import AddTaskForm, TodoItemForm, TodoItemExportForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import ListView, DeleteView
from django.contrib import messages
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings


@login_required
def index(request):
    return HttpResponse('Примитивный ответ из приложения tasks')


def complete_task(request, uid):
    t = TodoItem.objects.filter(id=uid).first()
    t.is_completed = True
    t.save()
    return HttpResponse('Ok')


def delete_task(request, uid):
    TodoItem.objects.all().filter(id=uid).delete()
    messages.success(request, 'Задача удалена')
    return redirect(reverse('tasks:list'))


class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        u = self.request.user
        return u.tasks.all()


class TaskCreateView(View):

    def my_render(self, request, form):
        return render(request, 'tasks/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save(commit=False).owner = request.user
            form.save()
            return redirect(reverse('tasks:list'))
        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return self.my_render(request, form)


class TaskDetailView(DeleteView):
    model = TodoItem
    template_name = 'tasks/details.html'


class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect(reverse('tasks:list'))

        return render(request, 'tasks/edit.html', {'form': form, 'task': t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, 'tasks/edit.html', {'form': form, 'task': t})


class ExportTaskView(LoginRequiredMixin, View):
    def genetate_body(self, user, priorities):
        q = Q()
        if priorities['prio_high']:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities['prio_medium']:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities['prio_low']:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = 'Ваши задачи и приоритеты: \n'
        for t in list(tasks):
            if t.is_completed:
                body += f'[x] {t.description} ({t.get_priority_display()})\n'
            else:
                body += f'[ ] {t.description} ({t.get_priority_display()})\n'

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.genetate_body(request.user, form.cleaned_data)
            send_mail('Задачи', body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, 'Задачи были отправлены на почту {}'.format(email)
            )
        else:
            messages.error(
                request, 'Что-то пошло не так, попробуйте еще раз'
            )
        return redirect(reverse('tasks:list'))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, 'tasks/export.html', {'form': form})

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Создать задачу{% endblock %}

{% block main_content %}
    <h1>Создать задачу</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Добавить</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Задача {{ object.id }}{% endblock %}

{% block main_content %}
    <h1>Задача</h1>
    <p><b>Описание</b>: {{ object }}</p>
    <ul>
        <li>
            {% if object.is_completed %}
            Задача Выполнена
            {% else %}
            Задаче еще не выполнена
            {% endif %}
        </li>
        <li>
            <i class="far fa-calendar-alt"></i>&nbsp;
            Создана: {{ object.created | date:"Y-b-d H:i"}}
        </li>
        <li>
            <i class="far fa-clock"></i>&nbsp;
            {% if object.created != object.updated %}
            Последнее изменение: {{ object.updated | date:"Y-b-d H:i"}}
            {% else %}
            Изменеий не производилось
            {% endif %}
        </li>
        <li>
            <i class="far fa-edit"></i>&nbsp;<a href="{% url 'tasks:edit' pk=object.pk %}">Редактировать</a>
        </li>
    </ul>
    <i class="fas fa-clipboard-list"></i>
    <a href="{% url 'tasks:list' %}">Назад к списку задач</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменить задачу{% endblock %}

{% block main_content %}
    <h1>Изменить задачу</h1>
    <form action="{% url 'tasks:edit' pk=task.pk %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Добавить</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/export.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Экспорт{% endblock %}

{% block main_content %}
    <h1>Экспорт задач</h1>
    <p>На вашу почту придет письмо с задачами. Уточните список.</p>
    <form action="." method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Отправить</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}<script src="{% static 'js/script.js' %}"></script>{% endblock %}

{% block main_content %}
    <h1>Текущие задачи</h1>
    <p><i class="fa fa-download"></i>&nbsp;<a href='{% url "tasks:export" %}'>экспорт</a></p>
    <ul id="todo-list">
    {% for task in tasks %}
        {% if task.is_completed %}
        <li class="completed">
            <input class='checkbox' data-uid='{{ task.id }}' type='checkbox' disabled='disabled' checked='checked'/>
        {% else %}
        <li>
            <input class='checkbox' data-uid='{{ task.id }}' type='checkbox' />
        {% endif %}
            {% if task.priority == task.PRIORITY_HIGH %}
            <span class="badge badge-pill badge-danger">&nbsp;</span>
            {% elif task.priority == task.PRIORITY_MEDIUM %}
            <span class="badge badge-pill badge-secondary">&nbsp;</span>
            {% elif task.priority == task.PRIORITY_LOW %}
            <span class="badge badge-pill badge-success">&nbsp;</span>
            {% endif %}
            <a href='{% url "tasks:details" task.id %}'>{{ task }}</a>
            <a class="remove" href='{% url "tasks:delete" task.id %}'>X</a>
            <hr/>
        </li>
    {% endfor %}
    </ul>
{% endblock %}