accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

send/urls.py
from django.urls import path

from . import views

app_name = 'send'

urlpatterns = [
    path('', views.index),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailView.as_view(), name='details'),
    path('edit/<int:pk>', views.TaskEditView.as_view(), name='edit'),
    path('export/', views.ExportTaskView.as_view(), name='export'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('send/', include('send.urls', namespace='send')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}{% endblock %}</title>

    <link
            rel="stylesheet"
            href="{% static 'css/styles.css' %}"
    />

    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
            crossorigin="anonymous"
    />

    <script
            src="http://code.jquery.com/jquery-3.3.1.min.js">
    </script>

    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous">
    </script>

    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous">
    </script>

    {% block extra_head %}{% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="side_bar col">
                {% block side_bar %}
                {% if user.is_authenticated %}
                <p>{{ user.first_name }}</p>

                <ul>
                    <li><a href="{% url 'accounts:edit' %}">профиль</a></li>

                    <li><a href="{% url 'tasks:create' %}">добавить задачу</a></li>

                    <li><a href="{% url 'tasks:list' %}">задачи</a></li>

                    <li><a href="{% url 'accounts:logout' %}">выйти</a></li>

                </ul>
                {% endif %}
                {% endblock %}
            </div>

            <div class="main_content col-8">
                {% if massages %}
                <div class="row">
                    <ul class="massages">
                        {% for massage in massages %}
                        <li class="alert alert-{{ message.tags }} alert-dismissable">{{ massage }}<a href="#" class="close" data-dismiss="alert">X</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% block main_content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>